version: '2'

volumes:

    build: {}

services:

    db:
        build: docker/test-db
        image: camptocamp/c2cgeoportal-test-db

    mapserver:
        build: docker/test-mapserver
        image: camptocamp/c2cgeoportal-test-mapserver
        links:
        - db

    c2cgeoportal:
        image: camptocamp/geomapfish_build_dev:2.2
        links:
        - db
        - mapserver
        volumes:
        - build:/build
        - .:/src
        environment:
        - USER_NAME
        - USER_ID
        - GROUP_ID
        stdin_open: true
        tty: true
        command: ${RUN}
