[project]
name = 'qgis'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
"c2c.template" = "2.4.2"
fiona = "1.10.1"
defusedxml = "0.7.1"
lxml = "6.0.2"
