[tool.poetry]
name = 'c2cgeoportal'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
alabaster = "1.0.0" # theme
Pygments = "2.18.0"
Sphinx = "8.1.3"
sphinx-prompt = "1.9.0"
sphinx-jsonschema = "1.19.1"
sphinx-argparse = "0.5.2"
Sphinx-Substitution-Extensions = { extras = ["prompt"], version = "2024.10.17" }
sphinxcontrib-mermaid = "1.0.0"
c2cwsgiutils = ">=6.0.0.dev148"
tilecloud-chain = "1.22.0"
boto3 = { version = "1.35.72", optional = true }
