---
type: map
mapping:
  no_interpreted:
    type: seq
    required: True
    sequence:
      - type: str
  environment:
    type: seq
    required: True
    sequence:
      - type: map
        mapping:
          name:
            type: str
            required: True
          default:
            type: str
  interpreted:
    type: map
    required: True
    mapping:
      regex;(.+):
        type: any
  postprocess:
    type: seq
    required: True
    sequence:
      - type: map
        mapping:
          expression:
            type: str
            required: True
          vars:
            type: seq
            required: True
            sequence:
              - type: str
  vars:
    type: map
    required: True
    mapping:
      package:
        type: str
        required: True
      enable_admin_interface:
        type: bool
        required: True
      c2c.base_path:
        type: str
        required: True
      sqlalchemy.url:
        type: str
        required: True
      sqlalchemy.pool_recycle:
        type: int
      sqlalchemy.pool_size:
        type: int
      sqlalchemy.pool_overflow:
        type: int
      sqlalchemy.use_batch_mode:
        type: bool
      sqlalchemy_slave.url:
        type: str
        required: True
      sqlalchemy_slave.pool_recycle:
        type: int
      sqlalchemy_slave.pool_size:
        type: int
      sqlalchemy_slave.pool_overflow:
        type: int
      sqlalchemy_slave.use_batch_mode:
        type: bool
      default_max_age:
        type: int
        required: True
      srid:
        type: int
        required: True
      schema:
        type: str
        required: True

      dbsessions:
        type: map
        required: True
        mapping:
          regex;([a-z0-9-]+):
            type: map
            mapping:
              url:
                type: str
                required: true

      default_locale_name:
        type: str
        pattern: '[a-z][a-z]'
        required: True
      available_locale_names:
        type: seq
        required: True
        sequence:
          - type: str
            pattern: '[a-z][a-z]'
      interfaces:
        required: True
        type: seq
        sequence:
          - type: str
      default_interface:
        required: True
        type: str
      interfaces_config:
        required: True
        type: map
        mapping:
          regex;.+:
            type: map
            mapping:
              constants:
                type: map
                mapping:
                  regex;.+:
                    type: any
              dynamic_constants:
                type: map
                mapping:
                  regex;.+:
                    type: str
              routes:
                type: map
                mapping:
                  regex;.+:
                    type: map
                    mapping:
                      name:
                        type: str
                        required: True
                      elements:
                        type: seq
                        sequence:
                          - type: str
                      kw:
                        type: map
                        mapping:
                          regex;.+:
                            type: str
                      params:
                        type: map
                        mapping:
                          regex;.+:
                            type: text
                      dynamic_params:
                        type: map
                        mapping:
                          regex;.+:
                            type: str
              static:
                type: map
                mapping:
                  regex;.+:
                    type: map
                    mapping:
                      name:
                        type: str
                        required: True
                      append:
                        type: str
              redirect_interface:
                type: str
              do_redirect:
                type: bool
      authorized_referers:
        type: seq
        sequence:
          - type: str
      global_headers:
        type: seq
        sequence:
          - type: map
            mapping:
              pattern:
                type: str
                required: True
              headers:
                type: map
                required: True
                mapping:
                  regex;.+:
                    type: str
      headers:
        type: map
        required: True
        mapping:
          login: &header
            type: map
            required: True
            mapping:
              access_control_allow_origin:
                type: seq
                sequence:
                  - type: str
              access_control_max_age:
                required: True
                type: int
              cache_control_max_age:
                required: True
                type: int
          index: *header
          dynamic: *header
          config: *header
          api: *header
          themes: *header
          fulltextsearch: *header
          mapserver: *header
          tinyows: *header
          layers: *header
          print: *header
          profile: *header
          raster: *header
          shortener: *header
          error: *header

      urllogin:
        type: map
        required: True
        mapping:
          aes_key:
            type: str

      cache:
        type: map
        required: True
        mapping:
          backend:
            required: True
            type: str
          arguments:
            type: map
            mapping:
              regex;.+:
                type: any
      admin_interface:
        type: map
        required: True
        mapping:
          layer_tree_max_nodes:
            type: int
          map_base_layer:
            type: str
          map_x:
            type: int
            required: True
          map_y:
            type: int
            required: True
          map_zoom:
            type: int
            required: True
          map_fit_max_zoom:
            type: int
          available_metadata:
            type: seq
            required: True
            sequence:
              - type: map
                mapping:
                  name:
                    type: str
                    required: True
                  type:
                    type: str
                  regex:
                    type: str
                  error_message:
                    type: str
                  translate:
                    type: bool
          available_functionalities:
            type: seq
            required: True
            sequence:
              - type: map
                mapping:
                  name:
                    type: str
                    required: True
                  type:
                    type: str
                  regex:
                    type: str
                  error_message:
                    type: str
                  single:
                    type: bool
      layers:
        type: map
        required: True
        mapping:
          geometry_validation:
            type: bool
            required: True
          enum:
            type: map
            mapping:
              defaults: &free_dict
                type: map
                mapping:
                  regex;(.+):
                    type: any
              regex;(.+):
                type: map
                mapping:
                  defaults: *free_dict
                  dbsession:
                    type: str
                  attributes:
                    type: map
                    required: True
                    mapping:
                      regex;(.+):
                        type: map
                        mapping:
                          table:
                            type: str
                            required: True
                          column_name:
                            type: str
                          separator:
                            type: str
                          translate:
                            type: bool
      functionalities:
        type: map
        required: True
        mapping:
          anonymous:
            <<: *free_dict
            required: True
          registered:
            <<: *free_dict
            required: True
          available_in_templates:
            type: seq
            required: True
            sequence:
              - type: str
      tinyowsproxy:
        type: map
        required: True
        mapping:
          ogc_server:
            type: str
            required: True
          tinyows_url:
            type: str
            required: True
          proxy_online_resource:
            type: str
          online_resource:
            type: str
          tinyows_host:
            type: str
      api:
        type: map
        required: True
        mapping:
          ogc_server:
            type: str
            required: True
      fulltextsearch:
        type: map
        required: True
        mapping:
          defaultlimit:
            type: int
            required: True
          maxlimit:
            type: int
            required: True
          languages:
            type: map
            required: True
            mapping:
              regex;([a-z][a-z]):
                type: str
      reset_password:
        type: map
        required: True
        mapping: &send_email
          email_from:
            required: True
            type: str
          email_body:
            required: True
            type: str
          email_subject:
            required: True
            type: str
      welcome_email:
        type: map
        required: True
        mapping: *send_email
      smtp:
        type: map
        mapping:
          host:
            type: str
            required: True
          ssl:
            type: bool
          user:
            type: str
          password:
            type: str
          starttls:
            type: bool

      servers:
        <<: *free_dict
        required: True
      host_forward_host:
        type: seq
        sequence:
          - type: str
      raster:
        <<: *free_dict
        required: True
      shortener:
        type: map
        required: True
        mapping:
          <<: *send_email
          base_url:
            type: str
            required: True
          allowed_hosts:
            type: seq
            sequence:
              - type: str
          length:
            type: int
      hide_capabilities:
        type: bool
        required: True
      resourceproxy:
        type: map
        required: True
        mapping:
          targets:
            type: map
            required: True
            mapping:
              regex;(.+):
                type: str
          allowed_headers:
            type: seq
            required: True
            sequence:
              - type: str
                unique: yes
      print_url:
        type: str
        required: True
      pdfreport:
        type: map
        mapping:
          print_url:
            type: str
          layer-defaults: *free_dict
          map-defaults: *free_dict
          layers:
            type: map
            mapping:
              regex;(.+):
                type: map
                mapping:
                  ogc_server:
                    type: str
                    required: True
                  check_credentials:
                    type: bool
                    required: True
                  srs:
                    type: str
                    required: True
                  spec:
                    type: any
                  map: &map
                    type: map
                    mapping:
                      backgroundlayers:
                        type: seq
                        required: True
                        sequence:
                          - type: str
                      imageformat:
                        type: str
                        required: True
                        pattern: '[a-z]+/[a-z]+'
                      zoomType:
                        type: str
                        required: True
                      minScale:
                        type: int
                        required: True
                      style:
                        type: any
                        required: True
                  maps:
                    type: seq
                    sequence:
                      - *map
      subdomain_url_template:
        type: str
      subdomains:
        type: seq
        sequence:
          - type: str

      lingua_extractor:
        type: map
        mapping:
          host_map:
            type: map
            mapping:
              regex;(.+):
                type: map
                mapping:
                  netloc:
                    type: str
                  scheme:
                    type: str
                  verify:
                    type: any
                  headers:
                    type: map
                    mapping:
                      regex;(.+):
                        type: str

      checker:
        type: map
        required: True
        mapping:
          forward_host:
            type: bool
          base_internal_url:
            type: str
          fulltextsearch:
            type: map
            required: True
            mapping:
              level:
                type: int
                required: True
              search:
                type: str
                required: True
              disable:
                type: bool
          lang:
            type: map
            required: True
            mapping:
              level:
                type: int
                required: True
              files:
                type: seq
                required: True
                sequence:
                  - type: str
          print:
            type: map
            required: True
            mapping:
              level:
                type: int
                required: True
              spec:
                type: any
                required: False
          routes: &routes
            type: map
            required: True
            mapping:
              disable:
                type: seq
                required: True
                seq:
                  - type: str
              routes:
                type: seq
                required: True
                seq:
                  - type: map
                    mapping:
                      level:
                        type: int
                        required: True
                      name:
                        type: str
                        required: true
                      checker_name:
                        type: str
                      params: &params
                        type: map
                        mapping:
                          regex;([a-zA-Z0-9_\-~\.]+):
                            type: str
                            pattern: |-
                              [a-zA-Z0-9_\-~\.]+
          phantomjs: *routes
          themes:
            type: map
            required: True
            mapping:
              level:
                type: int
                required: True
              params: *params
              interfaces:
                type: map
                mapping:
                  regex;([a-z]+):
                    type: map
                    mapping:
                      params: *params
          regex;(.+):
            type: any
      check_collector:
        type: map
        required: True
        mapping:
          hosts:
            type: seq
            required: True
            sequence:
              - type: map
                mapping:
                  display:
                    type: str
                    required: True
                  url:
                    type: str
                    required: True
                  level:
                    type: int
          max_level:
            type: int
            required: True
          level:
            type: int
            required: True
      regex;(.+):
        type: any
