---
checks:
  required_workflows: False
  versions: False
  codespell:
    ignore_re:
      - CONST_create_template/.*
      - geoportal/testgeomapfishapp_geoportal/locale/.*
      - geoportal/testgeomapfishapp_geoportal/static-ngeo/js/apps/Controller.*\.js
